### ISSUE TITLE
Create a global data dynamic memory allocator

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#1]
- [ ] Design a dynamic memory allocator that pulls memory from a single large array in global memory
- [ ] Add the size of the array to the config file
- [ ] Implement `global_init`
- [ ] Implement `global_malloc`
- [ ] Implement `global_realloc`
- [ ] Implement `global_free`
- [ ] Add test cases to confirm no mangling of memory locations can be seen

**Comment by warrenyun** [comment]
this looks cool
