### ISSUE TITLE
Create an implementation of a generic list

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#2]
- [ ] Design an implementation for a generic list
- [ ] Implement `list_init`
- [ ] Implement `list_free`
- [ ] Implement `list_add`
- [ ] Implement `list_remove`
- [ ] Implement `list_clear`
- [ ] Implement `list_contains`
- [ ] Implement `list_size`
- [ ] Implement `list_to_array`
- [ ] Add test cases for each function
- [ ] Check for memory leaks

**Comment by Altanis** [comment]
close this issue
