### ISSUE TITLE
Create an implementation of a generic queue

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/sos#4]
- [ ] Design an implementation for a generic queue
- [ ] Implement `queue_init`
- [ ] Implement `queue_free`
- [ ] Implement `queue_empty`
- [ ] Implement `queue_size`
- [ ] Implement `queue_enqueue`
- [ ] Implement `queue_dequeue`
- [ ] Implement `queue_peek`
- [ ] Add test cases for each function
- [ ] Check for memory leaks

**Comment by farhannaqib** [comment]
🤓
